### ISSUE TITLE
post /task/

### ISSUE THREAD

**Issue by crisone** [YunYinORG/YunYinService#7]
请求值
fid	3
pid	1
copies 1
color 0
isdouble 0
requirements fff

返回值
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'double' in 'field list'' in /var/www/html/app/library/Service/Db.php:63
Stack trace:
#0 /var/www/html/app/library/Service/Db.php(63): PDO-&gt;prepare('INSERT INTO`tas...')
#1 /var/www/html/app/library/Service/Db.php(152): Service\Db-&gt;init('INSERT INTO`tas...', Array)
#2 /var/www/html/app/library/Model.php(359): Service\Db-&gt;execute('INSERT INTO`tas...', Array)
#3 /var/www/html/app/library/Model.php(266): Model-&gt;execute('INSERT INTO`tas...', Array)
#4 [internal function]: Model-&gt;insert(Array)
#5 /var/www/html/app/models/Facade.php(130): call_user_func_array(Array, Array)
#6 /var/www/html/app/controllers/Task.php(58): FacadeModel::__callStatic('insert', Array)
#7 /var/www/html/app/controllers/Task.php(58): TaskModel::insert(Array)
#8 [internal function]: TaskController-&gt;POST_indexAction()
#9 /var/www/html/index.php(4): Yaf_Application-&gt;run()
#10 {main}
  thrown in <b>/var/www/html/app/library/Service/Db.php</b> on line <b>63</b><br />

**Comment by New-Future** [comment]
更新数据库
